---

template_path: email-spf.yaml

stack_tags:
   Purpose: dns
   domain: {{ domain }}

parameters:
   Domain: {{ domain }}
   HostedZoneId: {{ hosted_zone_id }}
   Value: v=spf1 include:spf.messagingengine.com ?all
